# Generated by ChatGPT on 2026-01-29
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScreeningLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=512)),
                ("matches_found", models.PositiveIntegerField(default=0)),
                ("high_risk_matches", models.PositiveIntegerField(default=0)),
                ("min_score_threshold", models.PositiveIntegerField(default=90)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
